# Latest documentation available at https://omines.github.io/datatables-bundle/#configuration
datatables:
    # Set options, as documented at https://datatables.net/reference/option/
    options:
        lengthMenu : [10, 25, 50, 100, 250, 500, 1000, 2500]
        pageLength: 10
        dom: "<'#busqueda.col-sm-2 text-start'f><'row' <'col-sm-5' B><'col-sm-7 text-end' i><'col-sm-12' tr>><'row' <'col-sm-6'l><'col-sm-6'p>>"
        

    template_parameters:
        # Example classes to integrate nicely with Bootstrap 3.x
        className: 'table table-striped table-bordered table-hover data-table'

    # Default HTTP method to be used for callbacks
    method: POST # One of "GET"; "POST"

    # You can for example override this to "tables" to keep the translation domains separated nicely
    translation_domain: 'messages'

     # Where to persist the current table state automatically
    persist_state: local # One of "none"; "query"; "fragment"; "local"; "session"    

