doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                schema_filter: "~^(?!auditoria|messenger_messages)~"
                url: '%env(resolve:DATABASE_URL)%'

            iol:
                charset: AL32UTF8
                url: '%env(resolve:DATABASE_IOL_URL)%'

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        
        entity_managers:
            default:    
                connection: default        
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                dql:
                    datetime_functions:
                        toChar: DoctrineExtensions\Query\Postgresql\DateFormat
                    string_functions:
                        toUpper: App\DQL\UpperPostgresql
                        toCast: App\DQL\CastPostgresql
            iol:
                connection: iol
                mappings:
                    iol:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/IOL'
                        prefix: 'App\Entity\IOL'
                        alias: iol
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
